/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    RadioGroupDescription: typeof import('@headlessui/vue')['RadioGroupDescription']
    RadioGroupLabel: typeof import('@headlessui/vue')['RadioGroupLabel']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('@headlessui/vue')['Tab']
    TabGroup: typeof import('@headlessui/vue')['TabGroup']
    TabList: typeof import('@headlessui/vue')['TabList']
    TabPanel: typeof import('@headlessui/vue')['TabPanel']
    TabPanels: typeof import('@headlessui/vue')['TabPanels']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
