name: 🛠 Tests-CI

on:
  pull_request:

env:
  NODE_ENV: prod

jobs:
  StyleGuides_checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: ⚙️ Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 🔧 Install
        run: pnpm install --frozen-lockfile

      - name: 📖 Lint
        run: pnpm run lint

      - name: ☑️ Type checking
        run: pnpm run type:check

  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: ⚙️ Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 🔧 Install
        run: pnpm install --frozen-lockfile

      - name: 🏗 Build
        run: pnpm run build
      
      - name: ✅ Tests
        run: pnpm run test

  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: ⚙️ Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 🔧 Install
        run: pnpm install --frozen-lockfile

      - name: 🏗 Build
        run: pnpm run build
